wandb_version: 1

C:
  desc: null
  value:
  - 0.001
  - 0.01
  - 0.1
  - 1.0
  - 10.0
  - 100.0
kernel:
  desc: null
  value:
  - linear
  - rbf
  - poly
gamma:
  desc: null
  value:
  - 0.001
  - 0.01
  - 0.1
  - 1.0
  - 10.0
  - 100.0
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728273950
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.17.3
      8:
      - 4
      - 5
      13: darwin-arm64
