wandb_version: 1

n_estimators:
  desc: null
  value:
  - 50
  - 100
  - 200
  - 300
max_depth:
  desc: null
  value:
  - 3
  - 5
  - 7
  - 10
learning_rate:
  desc: null
  value:
  - 0.001
  - 0.005623413251903491
  - 0.03162277660168379
  - 0.1778279410038923
  - 1.0
subsample:
  desc: null
  value:
  - 0.7
  - 0.8
  - 0.9
  - 1.0
colsample_bytree:
  desc: null
  value:
  - 0.7
  - 0.8
  - 0.9
  - 1.0
gamma:
  desc: null
  value:
  - 0
  - 0.1
  - 0.3
  - 0.5
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.17.3
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1728274726
    t:
      1:
      - 5
      - 6
      - 53
      - 55
      2:
      - 5
      - 6
      - 53
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.12.2
      5: 0.17.3
      8:
      - 4
      - 5
      13: darwin-arm64
